# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#  Get new wiki
  - rm -fr docs
  - git clone https://github.com/gama-platform/gama.wiki.git docs
#  - sh script/autoHeader.sh
#  Move static elements in right position
  - rm -fr website/static/resources
  - mv {docs,website/static}/resources 
#  Compile website
  - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

