# .travis.yml
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  yarn: true
before_script:
#  Setup
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
#  Get new wiki
  - git clone https://github.com/gama-platform/gama.wiki.git
#  Reorganise folders to be more Docusaurus-friendly
  - sh ./script/unstructurize.sh
  - sh ./script/link_fixer.sh
  #- sh script/autoHeader.sh
script:
#  Compile website
  - cd website && npm install && GIT_USER="${GH_NAME}" USE_SSH=true npm run publish-gh-pages
